version: "3"
services:
  db:
    image: mariadb:10.4
    container_name: dsoo_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes: 
      - "./data:/var/lib/mysql"
    ports: 
      - 3308:3306
    environment:
      MYSQL_DATABASE: datos
      MYSQL_ROOT_PASSWORD: pass

  phpmyadmin:
    container_name: dsoo_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - '8021:80'
    environment:
      PMA_HOST: dsoo_mysql
      MYSQL_ROOT_PASSWORD: pass
